apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-sync-deployment
  namespace: sre-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-sync
  template:
    metadata:
      labels:
        app: image-sync
    spec:
      containers:
      - name: image-sync-container
        image: reg.redrock.team/sre/image_sync:v1.0.2
        command: ["/bin/bash", "-c"]
        args:
          - /usr/bin/image-sync.sh
        env:
        - name: IMAGES
          valueFrom:
            configMapKeyRef:
              name: image-config
              key: images
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
        - name: docker-credentials
          mountPath: /root/.docker
      volumes:
      - name: docker-credentials
        secret:
          secretName: image-sync
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
